### ISSUE TITLE
Form doesn't return anything

### ISSUE THREAD

**Issue by cho-is** [RanadeepPolavarapu/django-lockdown#1]
When I try to login nothing happens

`live_settings.py`

```
LOCKDOWN_PASSWORDS = ('blabla', )

INSTALLED_APPS += (
    'lockdown',
)

MIDDLEWARE_CLASSES += (
    'lockdown.middleware.LockdownMiddleware',
)
```

Django 1.7.6

**Comment by RanadeepPolavarapu** [comment]
Hi @cho-is,

I will fix it this weekend. Sorry, I've been busy with school.

Thank You,
Ranadeep

**Comment by cho-is** [comment]
I didn't dig too much but if you let me know what's the error I can make a pull request

**Comment by RanadeepPolavarapu** [comment]
Hey @cho-is ,

My apologies in the delay of fixing this, I was very busy with school. 

I did end up fixing a Py2 to Py3 bug. Please try to install using the new updated installation instructions. I couldn't reproduce your specific error however, please try this current version and let me know if this issue still persists.

58bb9aef10113f1fec1bf870323a2d643a995e0e

Thank You,
Ranadeep

**Comment by RanadeepPolavarapu** [comment]
Tested and working under Django 1.8 as well.

**Comment by cho-is** [comment]
Awesome, closing it.

**Comment by cho-is** [comment]
Still happening:
Django 1.8.5
Python 2.7

**Comment by cho-is** [comment]
sorry the issue was related with SESSION_COOKIE_DOMAIN settings

**Comment by RanadeepPolavarapu** [comment]
Hey, glad it's working. Please do let me know if any other issues arise :).
